package com.assesment.cycle.constants;

public enum ReportTypes {
	DAY_WISE_HIGHEST_DISTANCE_TRAVELER,
	OVERALL_HIGHEST_DISTANCE_TRAVELER,
	DAY_WISE_EARLY_TRAVELER,
	OVERALL_EARLY_TRAVELER,
	LONGEST_TIME_TRAVELER
}
